# -*- coding: utf-8 -*-
"""333.15 K single-temperature, multi-initial-state CatMAP recovery.

This module is a numerical-method change only.  The original DFT input,
eight elementary reactions, effective activities, and target temperature are
unchanged.  Every trial is solved directly at [333.15 K, 1.0].

CatMAP's official numbers solver consumes ``numbers_map`` values as initial
guesses.  Therefore each physically interpretable coverage seed is converted
to the native squared-numbers representation before the independent run.
Only roots that pass the project's eight-step flux, gas-balance, coverage and
relative-residual checks at two precision levels are candidates for promotion.
At least two different initial states must also agree in log10(TOF).

The former high-temperature bridge output under ``analysis_ooh/recovery_v2``
is preserved as historical evidence but is no longer read or generated by
this recovery path.
"""
from __future__ import annotations

import math
import os
import pickle
from contextlib import redirect_stderr, redirect_stdout
from pathlib import Path

import numpy as np
import pandas as pd

import run_ooh_analysis as core


SINGLE_TEMPERATURE_ROOT = core.OUTPUT / "recovery_single_temperature"
TARGET_TEMPERATURE = 333.15
TARGET_PRESSURE = 1.0
MULTI_START_LOG10_TOL = core.TOF_STABILITY_LOG10_TOL
REFINED_STAGES = ((260, "1e-180"), (360, "1e-260"), (460, "1e-340"))

# The first four are the requested physically motivated starts.  H2O, Ha and
# Hb cover common poisoning/intermediate-dominated alternatives without using
# any temperature other than the target condition.
INITIAL_DOMINANTS = (
    ("vacant", "vacant"),
    ("OOH_dominant", "OOH_s"),
    ("OH_dominant", "OH_s"),
    ("O_dominant", "O_s"),
    ("alkene_dominant", "C6H12_s"),
    ("water_dominant", "H2O_s"),
    ("Ha_dominant", "Ha_s"),
    ("Hb_dominant", "Hb_s"),
)

# Extra 333.15 K starts used by the independent branch-audit expansion.  They
# deliberately vary both composition and vacancy fraction; they do not alter
# the model's thermodynamic or kinetic parameters.
EXPANDED_MIXES = (
    ("OOH_O_mix", {"OOH_s": 0.49, "O_s": 0.49, "vacant": 0.02}),
    ("OOH_OH_mix", {"OOH_s": 0.49, "OH_s": 0.49, "vacant": 0.02}),
    ("alkene_OOH_mix", {"C6H12_s": 0.49, "OOH_s": 0.49, "vacant": 0.02}),
    ("vacant_10pct", {"OOH_s": 0.90, "vacant": 0.10}),
    ("balanced_adsorbates", {"all_adsorbates": 0.99, "vacant": 0.01}),
)


def _boolean(series: pd.Series) -> pd.Series:
    return series.astype(str).str.lower().eq("true")


def _target_present(coverage_map) -> bool:
    """Return whether a map contains the sole target descriptor point."""
    return any(
        abs(float(pt[0]) - TARGET_TEMPERATURE) < 1e-5
        and abs(float(pt[1]) - TARGET_PRESSURE) < 1e-7
        for pt, _ in (coverage_map or [])
    )


def _compare_independent_seeds(
    valid: list[dict], limit: float = MULTI_START_LOG10_TOL
) -> dict:
    """Require two starts to reproduce one complete validated root.

    Older bookkeeping rows do not contain the captured state vectors, so the
    historical TOF-only fallback is retained for metadata tests and old CSVs.
    New CatMAP runs capture the full coverage and rate vectors and use those as
    the primary equality criterion; TOF is only an auxiliary check.
    """
    from mpmath import mp

    eligible = [
        v for v in valid
        if (
            v.get("quality_pass") is True
            and v.get("refinement_stable") is True
            and math.isfinite(float(v.get("log10_net_C6H12O", float("nan"))))
        )
    ]
    values = [float(v["log10_net_C6H12O"]) for v in eligible]
    delta = max(values) - min(values) if values else float("nan")

    def vectors_match(left: dict, right: dict) -> bool:
        coverage_left = left.get("full_coverage_vector_high_precision")
        coverage_right = right.get("full_coverage_vector_high_precision")
        rates_left = left.get("net_rate_vector_high_precision")
        rates_right = right.get("net_rate_vector_high_precision")
        if not all((coverage_left, coverage_right, rates_left, rates_right)):
            return abs(
                float(left["log10_net_C6H12O"])
                - float(right["log10_net_C6H12O"])
            ) <= limit
        if left.get("coverage_order") != right.get("coverage_order"):
            return False
        if left.get("numbers_order") and right.get("numbers_order"):
            if left["numbers_order"] != right["numbers_order"]:
                return False
        left_c = [mp.mpf(value) for value in str(coverage_left).split(";")]
        right_c = [mp.mpf(value) for value in str(coverage_right).split(";")]
        left_r = [mp.mpf(value) for value in str(rates_left).split(";")]
        right_r = [mp.mpf(value) for value in str(rates_right).split(";")]
        if len(left_c) != len(right_c) or len(left_r) != len(right_r):
            return False
        coverage_abs = max(abs(a - b) for a, b in zip(left_c, right_c))
        rate_scale = max([abs(value) for value in left_r + right_r] + [mp.mpf(1)])
        rate_rel = max(abs(a - b) for a, b in zip(left_r, right_r)) / rate_scale
        tof_delta = abs(
            mp.mpf(str(left["log10_net_C6H12O"]))
            - mp.mpf(str(right["log10_net_C6H12O"]))
        )
        return (
            coverage_abs <= mp.mpf("1e-8")
            and rate_rel <= mp.mpf("1e-6")
            and tof_delta <= mp.mpf(str(limit))
        )

    matching_pairs = []
    for i, left in enumerate(eligible):
        for right in eligible[i + 1:]:
            if (
                left.get("seed_id") is not None
                and right.get("seed_id") is not None
                and left.get("seed_id") == right.get("seed_id")
            ):
                continue
            if vectors_match(left, right):
                matching_pairs.append((left, right))
    return {
        "independent_seed_validated_count": len(eligible),
        "independent_seed_delta_log10_TOF": float(delta),
        "independent_seed_matching_pair_count": len(matching_pairs),
        "independent_seed_agreement": bool(matching_pairs),
    }


def _store_single_verified_seed(point, coverages, numbers, path: Path) -> None:
    """Write only native CatMAP maps for one initial state."""
    if numbers is None:
        raise ValueError("A numbers_solver warm start requires numbers_map")
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        # Use ordinary Python floats in the seed file.  CatMAP converts them
        # back to its active mpmath precision during the run; this keeps the
        # input pickle portable and avoids persisting an mpmath context.
        "coverage_map": [[list(map(float, point)), list(map(float, coverages))]],
        "numbers_map": [[list(map(float, point)), list(map(float, numbers))]],
    }
    with path.open("wb") as fh:
        pickle.dump(payload, fh, protocol=2)


def _make_initial_coverages(
    adsorbate_names: list[str], dominant: str, epsilon: str = "1e-12"
) -> list:
    """Create one valid one-site coverage vector at the target condition."""
    from mpmath import mp

    small = mp.mpf(epsilon)
    total_entries = len(adsorbate_names) + 1  # adsorbates plus vacant site
    coverages = [small] * total_entries
    if dominant == "vacant":
        dominant_index = len(adsorbate_names)
    else:
        if dominant not in adsorbate_names:
            raise ValueError(
                f"Initial-state species {dominant!r} is not in CatMAP adsorbates "
                f"{adsorbate_names!r}"
            )
        dominant_index = adsorbate_names.index(dominant)
    coverages[dominant_index] = 1 - small * (total_entries - 1)
    return coverages


def _make_mixed_initial_coverages(
    adsorbate_names: list[str], weights: dict[str, float], epsilon: str = "1e-12"
) -> list:
    """Create a strictly non-negative mixed state with an explicit vacancy."""
    from mpmath import mp

    old_dps = mp.dps
    mp.dps = max(old_dps, 100)
    try:
        small = mp.mpf(epsilon)
        total_entries = len(adsorbate_names) + 1
        coverages = [small] * total_entries
        vacancy_index = len(adsorbate_names)
        usable = mp.mpf("1.0") - small * total_entries
        if "all_adsorbates" in weights:
            each = (
                usable * mp.mpf(str(weights["all_adsorbates"]))
                / len(adsorbate_names)
            )
            for index in range(len(adsorbate_names)):
                coverages[index] += each
        for species, fraction in weights.items():
            if species in {"vacant", "all_adsorbates"}:
                continue
            if species not in adsorbate_names:
                raise ValueError(f"Mixed seed species {species!r} is not configured")
            coverages[adsorbate_names.index(species)] += (
                usable * mp.mpf(str(fraction))
            )
        if "vacant" in weights:
            coverages[vacancy_index] += (
                usable * mp.mpf(str(weights["vacant"]))
            )
        if abs(mp.fsum(coverages) - mp.mpf("1.0")) > mp.mpf("1e-80"):
            raise ValueError(f"Mixed seed does not sum to one: {weights!r}")
        return coverages
    finally:
        mp.dps = old_dps


def _coverage_to_squared_numbers(coverages: list) -> list:
    """Convert coverage fractions to CatMAP's default squared-number vector."""
    from mpmath import mp

    values = [mp.mpf(str(value)) for value in coverages]
    if not values or any(value < 0 for value in values):
        raise ValueError("Coverage seed must contain non-negative values")
    if abs(mp.fsum(values) - 1) > mp.mpf("1e-30"):
        raise ValueError("Coverage seed must sum to one")
    return [mp.sqrt(value) for value in values]


def _build_initial_seed_files(
    surface: str,
    output_root: Path = SINGLE_TEMPERATURE_ROOT,
    expanded: bool = False,
) -> list[dict]:
    """Build target-point seed files using CatMAP's actual species order."""
    from catmap import ReactionModel

    factory_root = output_root / "seed_factory" / surface
    factory_root.mkdir(parents=True, exist_ok=True)
    config = core.create_single_surface_setup(
        surface,
        factory_root,
        precision=100,
        tolerance="1e-50",
        numbers_solver=True,
    )
    previous = Path.cwd()
    try:
        os.chdir(factory_root)
        model = ReactionModel(setup_file=config.name)
        adsorbates = list(model.solver.adsorbate_names)
        site_count = len(model.solver.site_names) - 1
        if site_count != 1:
            raise ValueError(
                "The configured multi-start conversion expects one surface site; "
                f"CatMAP reported {site_count}"
            )
    finally:
        os.chdir(previous)

    records = []
    seed_specs = [
        (seed_id, dominant, None) for seed_id, dominant in INITIAL_DOMINANTS
    ]
    if expanded:
        seed_specs.extend(
            (seed_id, seed_id, weights) for seed_id, weights in EXPANDED_MIXES
        )
    for seed_id, dominant, mixed_weights in seed_specs:
        if mixed_weights is None:
            coverages = _make_initial_coverages(adsorbates, dominant)
        else:
            coverages = _make_mixed_initial_coverages(adsorbates, mixed_weights)
        numbers = _coverage_to_squared_numbers(coverages)
        numbers_floats = [float(value) for value in numbers]
        coverage_floats = [float(value) for value in coverages]
        numbers_norm = sum(value * value for value in numbers_floats)
        roundtrip = [
            value * value / numbers_norm for value in numbers_floats
        ]
        path = output_root / "seeds" / surface / f"{seed_id}.pkl"
        _store_single_verified_seed(
            [TARGET_TEMPERATURE, TARGET_PRESSURE], coverages, numbers, path
        )
        records.append(
            {
                "surface": surface,
                "seed_id": seed_id,
                "dominant_initial_species": dominant,
                "temperature_K": TARGET_TEMPERATURE,
                "pressure": TARGET_PRESSURE,
                "seed_file": str(path.resolve()),
                "adsorbate_order": ";".join(adsorbates),
                "coverage_vector": ";".join(str(value) for value in coverages),
                "numbers_vector": ";".join(str(value) for value in numbers),
                "vector_length": len(numbers),
                "site_count": site_count,
                "coverage_sum": sum(coverage_floats),
                "min_coverage": min(coverage_floats),
                "theta_roundtrip_max_abs_error": max(
                    abs(a - b) for a, b in zip(coverage_floats, roundtrip)
                ),
            }
        )
    return records


def _run_seed_refinement(
    surface: str,
    seed: dict,
    output_root: Path = SINGLE_TEMPERATURE_ROOT,
) -> tuple[dict, list[dict]]:
    """Run matched precision stages from one fixed 333.15 K initial state."""
    seed_file = Path(seed["seed_file"]).resolve()
    previous = None
    attempts = []
    accepted = None
    for stage_index, (precision, tolerance) in enumerate(REFINED_STAGES, 1):
        root = (
            output_root
            / "target"
            / surface
            / seed["seed_id"]
            / f"stage_{stage_index:02d}"
        )
        try:
            root.mkdir(parents=True, exist_ok=True)
            stdout_log = root / "catmap_stdout.txt"
            with stdout_log.open("w", encoding="utf-8") as stream:
                with redirect_stdout(stream), redirect_stderr(stream):
                    row = core.run_single_surface(
                        surface,
                        precision=precision,
                        tolerance=tolerance,
                        output_root=root,
                        seed_file=seed_file,
                        max_iterations=400,
                        max_bisections=5,
                        capture_state=True,
                    )
        except Exception as exc:
            row = {
                "surface": surface,
                "status": f"FAILED: {type(exc).__name__}: {exc}",
                "quality_status": "solver_failed",
                "quality_pass": False,
            }
        row.update(
            {
                "seed_id": seed["seed_id"],
                "dominant_initial_species": seed["dominant_initial_species"],
                "initial_temperature_K": TARGET_TEMPERATURE,
                "initial_seed_source": str(seed_file),
                "refinement_stage": stage_index,
                "refinement_stable": False,
                "refinement_delta_log10_TOF": float("nan"),
            }
        )
        if previous is not None:
            row.update(core.compare_refinement_runs(previous, row))
        attempts.append(dict(row))
        if row["refinement_stable"]:
            accepted = dict(row)
            accepted["quality_status"] = "validated_two_precisions"
            accepted["quality_pass"] = True
            break
        previous = row

    if accepted is not None:
        return accepted, attempts
    last = dict(attempts[-1])
    last["quality_pass"] = False
    last["refinement_stable"] = False
    last["quality_status"] = "not_stable_from_this_initial_state"
    return last, attempts


def recover_one_surface(
    surface: str,
    output_root: Path = SINGLE_TEMPERATURE_ROOT,
    expanded: bool = False,
) -> tuple[dict, list[dict], list[dict]]:
    """Run all fixed-temperature starts and apply cross-start validation."""
    output_root = Path(output_root)
    seeds = _build_initial_seed_files(
        surface, output_root=output_root, expanded=expanded
    )
    candidates = []
    trials = []
    for seed in seeds:
        result, attempts = _run_seed_refinement(
            surface, seed, output_root=output_root
        )
        candidates.append(result)
        trials.extend(attempts)

    valid = [
        row
        for row in candidates
        if row.get("quality_pass") is True
        and row.get("refinement_stable") is True
    ]
    agreement = _compare_independent_seeds(valid)
    result = dict(valid[0]) if valid else {"surface": surface}
    result.update(agreement)
    result["initial_seed_count"] = len(seeds)
    result["initial_seed_validated_count"] = len(valid)
    result["attempted_initial_states"] = ";".join(
        str(seed["seed_id"]) for seed in seeds
    )
    if agreement["independent_seed_agreement"]:
        result["quality_pass"] = True
        result["refinement_stable"] = True
        result["quality_status"] = "validated_cross_initial_state_and_precision"
        result["status"] = "solved"
    else:
        result["quality_pass"] = False
        result["refinement_stable"] = False
        result["quality_status"] = (
            "different_valid_steady_state_branches"
            if len(valid) >= 2
            else "insufficient_independent_valid_roots"
        )
        result["status"] = "not independently validated"
    return result, trials, seeds


def recover_unvalidated_surfaces(surfaces: list[str] | None = None) -> None:
    """Recover only unvalidated surfaces at 333.15 K; never use high-T paths."""
    base_file = core.OUTPUT / "dft_baseline.csv"
    if not base_file.exists():
        raise FileNotFoundError("Please run baseline CatMAP analysis first")
    baseline = pd.read_csv(base_file)
    existing_good = _boolean(baseline["quality_pass"]) & _boolean(
        baseline["refinement_stable"]
    )
    if not surfaces:
        selected = baseline.loc[~existing_good, "surface"].tolist()
    else:
        selected = list(dict.fromkeys(surfaces))
        invalid = set(selected) - set(core.SURFACES)
        if invalid:
            raise ValueError(f"Unknown catalyst surface names: {sorted(invalid)}")
        previous_good = set(baseline.loc[existing_good, "surface"])
        selected = [surface for surface in selected if surface not in previous_good]

    if not selected:
        print("All selected surfaces already meet the existing quality standard.")
        return

    SINGLE_TEMPERATURE_ROOT.mkdir(parents=True, exist_ok=True)
    all_results, all_trials, all_seeds, updated = [], [], [], []
    for surface in selected:
        print(f"\n====== 333.15 K multi-start recovery: {surface} ======")
        try:
            final, trials, seeds = recover_one_surface(surface)
        except Exception as exc:
            final = {
                "surface": surface,
                "status": f"FAILED: {type(exc).__name__}: {exc}",
                "quality_status": "recovery_exception",
                "quality_pass": False,
                "refinement_stable": False,
            }
            trials, seeds = [], []
        all_results.append(final)
        all_trials.extend(trials)
        all_seeds.extend(seeds)
        print(
            f"[{surface}] {final['quality_status']}; "
            f"validated initial states: {final.get('initial_seed_validated_count', 0)}"
        )

        if final.get("quality_pass") is True and final.get("refinement_stable") is True:
            updated.append(surface)
            for key, value in final.items():
                if key not in baseline.columns:
                    baseline[key] = np.nan
                baseline.loc[baseline["surface"].eq(surface), key] = value

    pd.DataFrame(all_seeds).to_csv(
        SINGLE_TEMPERATURE_ROOT / "seed_definitions.csv", index=False
    )
    pd.DataFrame(all_trials).to_csv(
        SINGLE_TEMPERATURE_ROOT / "seed_trials.csv", index=False
    )
    pd.DataFrame(all_results).to_csv(
        SINGLE_TEMPERATURE_ROOT / "recovery_results.csv", index=False
    )

    if updated:
        backup = SINGLE_TEMPERATURE_ROOT / "baseline_before_recovery.csv"
        if not backup.exists():
            import shutil

            shutil.copy2(base_file, backup)
        baseline.to_csv(base_file, index=False)
        merged = core.read_data().merge(baseline, on="surface", how="left")
        good = _boolean(merged["quality_pass"]) & _boolean(
            merged["refinement_stable"]
        )
        log_tof = pd.to_numeric(merged["log10_net_C6H12O"], errors="coerce")
        merged["eligible_for_tof_fit"] = good & np.isfinite(log_tof)
        merged.to_csv(core.OUTPUT / "OOH_TOF_results.csv", index=False)
        fit_data = merged.loc[merged["eligible_for_tof_fit"]]
        core.plot_linear(
            fit_data,
            "G_OOH_eV",
            "log10_net_C6H12O",
            "OOH_logTOF_linear.png",
            "OOH* formation energy (eV)",
            "log10(net epoxide TOF)",
            min_points=5,
        )

    print("\nRecovered validated surfaces:", len(updated), updated)
    print("Initial states:", SINGLE_TEMPERATURE_ROOT / "seed_definitions.csv")
    print("Trials and results:", SINGLE_TEMPERATURE_ROOT / "seed_trials.csv")
    print("Only 333.15 K was used; all DFT energies remain unchanged.")


if __name__ == "__main__":
    recover_unvalidated_surfaces()
